# prometheus/prometheus.yml
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-1:7071', 'kafka-2:7072', 'kafka-3:7073']

  # - job_name: 'kafka-connect'
  #   static_configs:
  #     - targets: ['connect:7074']

  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:7075']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
