{
 "title": "Kafka Topics and Consumer Groups",
 "description": "Monitor Kafka topics and consumer groups",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_topic_partitions{topic!~\"__consumer_offsets|_schemas\"},topic)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{topic=\"$topic\"},partition)"
    }
   },
   {
    "name": "consumergroup",
    "query": {
     "query": "label_values(kafka_consumergroup_members,consumergroup)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Preferred leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{topic=\"$topic\"}) - sum(kafka_topic_partition_leader_is_preferred{topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "In-Sync replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{topic=\"$topic\"}) - sum(kafka_topic_partition_in_sync_replica{topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Current offset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Number of partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Offset rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"$topic\"}[1m]))",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Current offset",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"$topic\"}",
     "legendFormat": "Partition {{ partition }}"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_topic_partition_under_replicated_partition{topic=\"$topic\"}",
     "legendFormat": "Partition {{ partition }}"
    }
   ]
  },
  { "title": "Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Preferred partition leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_leader_is_preferred{topic=\"$topic\", partition=\"$partition\"}"
    }
   ]
  },
  {
   "title": "Partition leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_leader{topic=\"$topic\", partition=\"$partition\"}"
    }
   ]
  },
  {
   "title": "Current partition offset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"$topic\", partition=\"$partition\"}"
    }
   ]
  },
  {
   "title": "Number of partition replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_replicas{topic=\"$topic\", partition=\"$partition\"}"
    }
   ]
  },
  {
   "title": "In-Sync partition replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_in_sync_replica{topic=\"$topic\", partition=\"$partition\"}"
    }
   ]
  },
  { "title": "Consumer groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Consumer group lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=\"$topic\", consumergroup=~\"$consumergroup\"}",
     "legendFormat": "{{consumergroup}}, Partition {{partition}}"
    }
   ]
  },
  {
   "title": "Consumer group lag by partition",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=\"$topic\", consumergroup=~\"$consumergroup\"}",
     "legendFormat": "{{consumergroup}}, Partition {{ partition }}"
    }
   ]
  },
  {
   "title": "Consumer group lag rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by(consumergroup) (rate(kafka_consumergroup_lag{topic=\"$topic\", consumergroup=~\"$consumergroup\"}[1m]))",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Consumer group offset by partition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset{topic=\"$topic\", consumergroup=~\"$consumergroup\"}",
     "legendFormat": "{{consumergroup}} Partition {{ partition }}"
    }
   ]
  },
  {
   "title": "Consumer group offset rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{topic=\"$topic\", consumergroup=~\"$consumergroup\"}[1m]))",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Topic size (not including replicas)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{topic=~\"$topic\"}) / sum(kafka_topic_partition_replicas{topic=~\"$topic\", partition=~\"$partition\"})",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Topic size by partition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_log_log_size{topic=\"$topic\"}",
     "legendFormat": "{{ pod }} partition {{ partition }}"
    }
   ]
  }
 ]
}